### ISSUE TITLE
How are phased candidate variants called?

### ISSUE THREAD

**Issue by nh13** [varlociraptor/varlociraptor#159]
Is this currently supported if we input phased candidate variants?

**Comment by dlaehnemann** [comment]
Nope. Varlociraptor will only use the `CHROM`, `POS`, `REF` and `ALT` fields, currently. And generally, I would think that for the calling, only local phasing among variants on the same read should be necessary, so that read probabilities are as accurate as possible. Global phasing could then be done afterwards. Or am I overlooking any important points, here?

For local phasing, there is a related project by @jafors: he is doing local phasing of variants for neoantigen prediction and has developed a tool called [microphaser](https://github.com/koesterlab/microphaser). This is currently only done with existing variant calls. But there is code and a lot of microphasing experience, and it would be great to eventually integrate this directly into varlociraptor. But that is a whole project in itself.

But as always: any thoughts and considerations are welcome. Especially actual use cases where you would want some particular phased output or pointers where it is important to use phasing input information!

**Comment by nh13** [comment]
@dlaehnemann 
> only local phasing among variants on the same read should be necessary
This would be great, though I would say that if variant A and B can be phased with one read, and B and C can be phased with another read, then I want to see A+B+C phased.  The easiest way is to look at the genotypes for all the input samples to create haplotypes based on the phased variants, and call those events based on how many reads support each haplotype.

The idea is that if freebayes, gatk, octopus, or other callers produce phased variants, I don't want to lose that information.  And I don't want to have to go back and post-process the `varlociraptor` output to try and add that.

> microphaser

This looks interesting, similar to read-backed phasing in GATK 3 (and others), but having haplotypes called versus variants is something that obviated the need for this, as it's much more power full call _haplotypes_ than individual alleles (overloading terms here).

> actual use cases where you would want some particular phased output or pointers where it is important to use phasing input information

We have clinical diagnostics and therapeutics companies that leverage phasing for interpretation of variants and their effect (unfortunately confidential).  You can see some edge cases that we've found GATK have issues with (eg. [here](https://github.com/broadinstitute/gatk/issues/6463)).  

Another option would be to pre-process the variants so that phased variants are not split across multiple records, but instead represented in a single record?  I think varlociraptor would then just treat them as any other allele.  But if the allele is longer than the read length, then would varlociraptor call the variant?

**Comment by dlaehnemann** [comment]
Thanks for the further clarifications and the pointer to the cases filed over at GATK. These will definitely be useful when dealing with phased candidate variant calls.

Preprocessing the candidate variants to be represented as MNVs is actually a very good idea. I think this should do the trick for varlociraptor (although I gladly stand corrected by @johanneskoester), at least for locally phased data and would even reduce redundant calculations, as the same haplotype will only be evaluated once instead of each variant on it separately. However, as phased regions get longer with improved upstream techniques (both sequencing and analysis), I could imagine that the pileups and the realignment would become unwieldy, so I guess some kind of windowing would need to be applied to haplotypes, while preserving haplotype linkage. Also, this makes parallelizing over genomic regions within a chromosome / contig more difficult, although I guess one could go for overlapping windows and then stitching those back together by preserving the original phasing info, afterwards.

**Comment by nh13** [comment]
Have you tried alleles longer than the read length?  Does that work?

**Comment by dlaehnemann** [comment]
I don't think we have explicitly tried that, but I wouldn't see why the code should barf on something like that. It feels a bit weird to have alleles spanning longer than reads, but I think this should be OK. So I would only think that it gets unwieldy at a point. But it's definitely something worth trying out!

**Comment by johanneskoester** [comment]
Technically, Varlociraptor could without problems interpret phased variants correctly, even complex combinations of different types (SNVs, MNVs, Indels). This could internally happen by encoding them as a chain of breakends. Manually, this could be already done even now. But I anyway had plans to implement an internal mode for this sooner or later (of course, help would be very welcome here).

A downside of phased input for Varlociraptor is however that the calling grammar becomes less powerful. Imagine you have a haplotype A>G .... C>T .... A>C. Not directly next to each other. Now, when you use the grammar to filter one or multiple samples against each other, and these three are encoded as a single haplotype, you will always reason over them as one item. E.g., having A>G .... C>C .... A>C in another sample would be considered as a denovo event. I am not sure whether that is worth it. My feeling is that a finer resolution (looking at variants individually) and phasing after the calling and filtering might be often more beneficial.

**Comment by johanneskoester** [comment]
Regarding microphaser, there are plans to reuse the fragment evidence of varlociraptor for the phasing with microphaser. This way, the grammar reasoning would remain untouched and at finest resolution, while you would still get statistically correct phased haplotypes for the effect prediction on the protein.

**Comment by nh13** [comment]
@johanneskoester for my use case, namely ensemble variant calling where I have candidates from multiple callers and want a unified framework for assessing those calls, phasing of variants is extremely beneficial, so any help is welcome.
